[package]
name = "pastbin"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.6.0"
rusqlite = "0.31.0"
rand = "0.8"
actix-files = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
